version: "3"
services:
  springboot-app:
    container_name: spring-boot-mysql-docker
    image: springboot-app-docker
    build: .
    restart: always
    ports:
      - 9000:9000
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root